//
//  MOCKDataProvider.swift
//  WeatherApp
//
//  Created by Viktor Prikolota on 18.05.2024.
//

import UIKit

struct CityWeatherData: Hashable {
    let id: Int
    let titleData: TitleViewData
    let dayHourlyDescription: String
    let dayHourlyData: [DayHourlyViewData]
    let dayData: [DayViewData]
}

struct TitleViewData: Hashable {
    let title: String
    let subtitle: String?
    let currentTemp: String
    let description: String
    let minTemp: String
    let maxTemp: String
}

struct DayHourlyViewData: Hashable {
    let hour: String
    let imageSystemName: String
    let temp: Double

    var id: String {
        "\(hour) \(imageSystemName) \(temp)"
    }
}

struct DayViewData: Hashable {
    let title: String
    let imageSystemName: String
    let minTemp: Double
    let maxTemp: Double
    let minDayTemp: Double
    let maxDayTemp: Double
    let currentTemt: Double?

    var id: String {
        "\(title) \(imageSystemName) \(minTemp) \(maxTemp) \(minDayTemp) \(maxDayTemp) \(String(describing: currentTemt))"
    }
}

extension CityWeatherData {
    static var emptyData: CityWeatherData {
        CityWeatherData(id: .currentPlaceId,
                        titleData: TitleViewData(title: "--",
                                                 subtitle: "--",
                                                 currentTemp: "--",
                                                 description: "--",
                                                 minTemp: "--",
                                                 maxTemp: "--"),
                        dayHourlyDescription: "--",
                        dayHourlyData:[],
                        dayData: [])

    }

    static var mockData: [CityWeatherData] {
        return [
            // MARK: - MOCK Data for first city
            //            CityWeatherData(titleData: TitleViewData(title: "Current palce",
            //                                                 subtitle: "BUENOS AIRES",
            //                                                 currentTemp: 19,
            //                                                 description: "Clear sky",
            //                                                 minTemp: 15,
            //                                                 maxTemp: 22),
            //                            dayHourlyDescription: "Cloudy weather from 9:00 to 19:00, mostly sunny weather is expected at 12:00",
            //                            dayHourlyData:[
            //                                DayHourlyViewData(hour: "Now Now Now",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "09",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "10",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "11",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "12",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "13",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "14",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "15",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "16",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "17",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                            ],
            //                            dayData: [
            //                                DayViewData(title: "Today",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "SU",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "MO",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "TU",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "WE",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "TH",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "FR",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "SA",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                            ]),
            //            // MARK: - MOCK Data for second city
            //            CityWeatherData(titleData: TitleViewData(title: "MOSCOW",
            //                                                 subtitle: "16:42",
            //                                                 currentTemp: 19,
            //                                                 description: "Clear sky",
            //                                                 minTemp: 15,
            //                                                 maxTemp: 22),
            //                            dayHourlyDescription: "Cloudy weather from 9:00 to 19:00, mostly sunny weather is expected at 12:00",
            //                            dayHourlyData:[
            //                                DayHourlyViewData(hour: "Now",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "09",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "10",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "11",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "12",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "13",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "14",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "15",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "16",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "17",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                            ],
            //                            dayData: [
            //                                DayViewData(title: "Today",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "SU",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "MO",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "TU",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "WE",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "TH",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "FR",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "SA",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                            ]),
            //            // MARK: - MOCK Data for third city
            //            CityWeatherData(titleData: TitleViewData(title: "PARIS",
            //                                                 subtitle: "14:42",
            //                                                 currentTemp: 19,
            //                                                 description: "Clear sky",
            //                                                 minTemp: 15,
            //                                                 maxTemp: 22),
            //                            dayHourlyDescription: "Cloudy weather from 9:00 to 19:00, mostly sunny weather is expected at 12:00",
            //                            dayHourlyData:[
            //                                DayHourlyViewData(hour: "Now",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "09",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "10",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "11",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "12",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "13",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "14",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "15",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "16",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                                DayHourlyViewData(hour: "17",
            //                                              imageSystemName: "sun.max.fill",
            //                                              temp: 15),
            //                            ],
            //                            dayData: [
            //                                DayViewData(title: "Today",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "SU",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "MO",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "TU",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "WE",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "TH",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "FR",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                                DayViewData(title: "SA",
            //                                        imageSystemName: "sun.max.fill",
            //                                        minTemp: 9,
            //                                        maxTemp: 22,
            //                                        minDayTemp: 11,
            //                                        maxDayTemp: 20,
            //                                        currentTemt: 15),
            //                            ])
        ]
    }
}

